### ISSUE TITLE
Chat card right-click action menu appears behind card or has missing options

### ISSUE THREAD

**Issue by mxvs** [coboye/sfrpg-modern-ui#10]
Hello!

I noticed today that when right-clicking a chat card to get the option menu to "Apply damage, Apply healing" etc.. the menu either appears **behind the chat card** and it is thus not clickable (happens to all chat cards except the very last one), or it shows up but it only has the "Make private" or "Reveal to everyone" option for the last chat card instead of all 4-5 options. See the screenshot below for the " appears behind the card" problem, you need to look carefully.

This happens both in the Foundry VTT stand-alone application and in Google Chrome. Version 1.1.1

<a href="https://imgbb.com/"><img src="https://i.ibb.co/44CvhDV/Capture.png" alt="Capture" border="0" /></a>

**Comment by coboye** [comment]
fixed in the next release
![image](https://user-images.githubusercontent.com/3914689/113362871-b39c5a80-934f-11eb-8c82-121562085ab6.png)
