### ISSUE TITLE
Some text and controls are impossible to read

### ISSUE THREAD

**Issue by LonePaladin** [coboye/sfrpg-modern-ui#30]
With certain settings, the text ends up in a similarly- or identically-colored field, making it impossible to read.

For reference, this is the "Configure Controls" screen on the default setting:
![image](https://user-images.githubusercontent.com/37523352/174206594-0a35f230-73f2-4089-8953-3f83815935fd.png)

And the same window with the "Starfinder Logo" setting:
![image](https://user-images.githubusercontent.com/37523352/174206678-fce215b8-eb01-4147-bae9-d6773e649670.png)

The "Terminal" setting is _barely_ readable:
![image](https://user-images.githubusercontent.com/37523352/174206778-5d6b30df-421b-4a8b-bf64-0ae86846f69e.png)

And the same for "Velstrac":
![image](https://user-images.githubusercontent.com/37523352/174206882-bfed90f9-959c-42a6-9f6e-5a70ba778b4c.png)

All the others are just as unreadable as in "Starfinder Logo".

**Comment by TheTwidgetITGuy** [comment]
Can confirm issue exists.  Love the module but keeping it disabled until the issue can be rectified.
